### ISSUE TITLE
Document/Test Workspace Support

### ISSUE THREAD

**Issue by humenda** [corrosion-rs/corrosion#56] opened 2020-09-30 14:06 UTC
Corrosion should offer the possibility to import crates using a Cargo.toml from a workspace. If that is already possible, it should be mentioned in the documentation. If not, a ToDo should be added.

**Comment by AndrewGaspar** [comment] 2020-10-01 00:07
Yeah, it's supported by design. I should probably add a test for it.

**Comment by humenda** [comment] 2020-10-01 07:13
Hi

>Yeah, it's supported by design. I should probably add a test for it.

Great, please add a note to the README. Thanks!

**Comment by ogoffart** [comment] 2020-10-06 13:58
I've actually tried to use corrosion with a repository that is having lots of crate in its workspace. But for the C++ build, i'm only interested in a single crate in this workspace (and its dependencies).
However, even if i do
```
corrosion_import_crate(MANIFEST_PATH "${CMAKE_SOURCE_DIR}/sub_dir/to/specific/Cargo.toml")
```
*every*  crate of the workspace (and even the one not in `default-members`) gets imported and build by default
I would like to only import the specific crate i'm interested in.

Not only because it recompile many crates i don't need, but also because it uses some name which i cannot use as target name as well.

**Comment by AndrewGaspar** [comment] 2020-10-06 14:01
Just filed https://github.com/AndrewGaspar/corrosion/issues/57

**Comment by jschwe** [comment] 2022-04-11 16:36
The current Readme documents the ability to import a workspace and we also have a test, so I'm closing this issue.

**Closed by jschwe** 2022-04-11 16:36 UTC
Labels: good first issue
