### ISSUE TITLE
support cmake LIBRARY_OUTPUT_PATH and EXECUTABLE_OUTPUT_PATH for rust cdylib

### ISSUE THREAD

**Issue by eric5f3759df** [corrosion-rs/corrosion#125] opened 2022-01-07 17:09 UTC
I found that when set rust to cdylib, the .dll can not generated at the same dir of LIBRARY_OUTPUT_PATH set by cmake.

**Comment by ratijas** [comment] 2022-01-08 14:09
Could you please give more details on what you have tried, and how it worked out (or rather didn't)?

**Comment by eric5f3759df** [comment] 2022-01-13 17:13
[cpp_rust.zip](https://github.com/corrosion-rs/corrosion/files/7864576/cpp_rust.zip)
consider this demo, the rust lib format is "cdylib", set camke binary output dir is /bin, by EXECUTABLE_OUTPUT_PATH and LIBRARY_OUTPUT_PATH set to /bin, but only cpp executable binary in /bin, the librust.dylib/rust.dll not output in bin
![1642093950686](https://user-images.githubusercontent.com/91838103/149376889-9e16dce4-9159-435d-95ac-890e21f8c60a.jpg)
.

**Comment by jschwe** [comment] 2022-02-06 16:34
To me this looks like a duplicate of #65.

**Closed by jschwe** 2022-02-06 16:34 UTC
Labels: duplicate
